name: default
created: '2026-01-29 23:30:13'
updated: '2026-01-29 23:30:13'
runs: 1
model: gemini-2.5-pro
turns:
- input: 我下一步想吃饭
  run: 1
  output: 'CALL: PLANNER | 安排下一步活动'
  tools_called: []
  expected: ''
  evaluation: ''
  meta: '{"tokens": 411, "cost": 0.0006, "duration_ms": 8757, "ts": "2026-01-29 23:30:13"}'
  history: []
