name: default
created: '2026-01-31 10:18:41'
updated: '2026-01-31 10:18:41'
runs: 1
model: gemini-2.5-pro
turns:
- input: 我之后想吃睡喝水
  run: 1
  output: 'CALL: PLANNER | 计划后续活动'
  tools_called: []
  expected: ''
  evaluation: ''
  meta: '{"tokens": 414, "cost": 0.0006, "duration_ms": 7093, "ts": "2026-01-31 10:18:41"}'
  history: []
